---
- name: Gregg desktop configuration
  hosts: localhost
  connection: local
  become: true

  vars:
    gregg_user: gregg
    ansible_user_name: ansible

    common_packages:
      - curl
      - wget
      - rsync
      - uptimed
      - htop
      - sudo

    desktop_packages:
      - flatpak
      - syncthing
      - remmina
      - vlc
      - nmap

  roles:
    - common
    - desktop
