---
- name: Gregg desktop configuration
  hosts: localhost
  connection: local
  become: true

  vars:
    gregg_user: gregg
    ansible_user_name: ansible

    desktop_packages:
      - flatpak
      - syncthing
      - remmina
      - vlc
      - nmap
      - gnome-software-plugin-flatpak
      - gnome-tweaks

  roles:
    - desktop
