---
- name: Gregg Docker host configuration
  hosts: localhost
  connection: local
  become: true

  vars:
    gregg_user: gregg
    ansible_user_name: ansible

    docker_user: gregg

  roles:
    - docker
